# Generated by Django 3.2.9 on 2021-11-19 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_student_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=50)),
                ('animal_name', models.CharField(max_length=50)),
                ('animal_age', models.IntegerField()),
                ('pure_breed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
